<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkDireccionGeneralDefensa</name>
   <tag></tag>
   <elementGuidId>240fffb4-1689-4a07-a4aa-8337c6485ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/div[2]/div[3]/div/div[2]/div[1]/h5/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[3]/div[2]/div[3]/div/div[2]/div[1]/h5/a</value>
   </webElementProperties>
</WebElementEntity>
