<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkEvaluacionSistema</name>
   <tag></tag>
   <elementGuidId>79078cf1-9bc9-4eba-a8bd-01033bdde9e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[3]/div[2]/div[3]/div/div[2]/div[2]/div/ul/li[1]/small/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[3]/div[2]/div[3]/div/div[2]/div[2]/div/ul/li[1]/small/a</value>
   </webElementProperties>
</WebElementEntity>
