<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonBuscarConsultaRecaudaciones</name>
   <tag></tag>
   <elementGuidId>7186eeac-b507-417d-834d-98460851bf9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/form/div/div/div/div/div[1]/div[16]/div/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div/div/form/div/div/div/div/div[1]/div[16]/div/a[2]</value>
   </webElementProperties>
</WebElementEntity>
