<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectDependenciaEmisora</name>
   <tag></tag>
   <elementGuidId>9e23e176-3eaf-4d2e-abae-bf6dd51355d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectDependBUI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectDependBUI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectDependBUI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>edicion.tramite.dependenciaBUI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>'(' + dependencia.codigo + ') ' + dependencia.nombre for dependencia in edicion.dependenciasBUI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>!edicion.tramite.soloBUI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>edicion.nuevaDepBUI()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Elija una dependencia --(1) Dirección Gral de Tesorería(2) Registro Civil (3) Sede Comunal Nº 1(4) Sede Comunal Nº 2(5) Subsede Comunal Nº 4(6) Sede Comunal Nº 5(8) Sede Comunal Nº 6(9) Sede Comunal Nº 7(10) Sede Comunal Nº 8(11) Sede Comunal Nº 9(12) Sede Comunal Nº 10(13) Sede Comunal Nº 11(14) EMUI(15) Sede Comunal Nº 13(16) Sede Comunal Nº 14 (17) Sede Comunal Nº 15(18) DAI - Edificio del Plata(19) Dirección General de Licencias(20) SS Transporte - Ordenamiento del Tránsito(21) Subsecretaria de Gestión de la Movilidad-GOTRE(22) SS Transporte - Estacionamiento momentáneo(23) Unidad Adm. de Control de Faltas - UACF(24) AGIP(25) Procuración General de la Ciudad(27) Dirección General Dependencias y Atención Primaria(28) DGTAL Vicejefatura de Gobierno(29) Mesa de Entradas(30) Cementerio Chacarita(31) Cementerio Flores(32) Sede Comunal Nº 12(33) Cementerio Recoleta(34) ACA Libertador(35) Hospital Piñero(36) Hospital Penna(37) Dir. Gral de Servicios de Seguridad Privada(38) AGC Habilitaciones-Inspecciones-Permisos(39) Dir. Gral de Defensa y Protecc al consumidor(40) Comunal Nº 3(41) Dirección Gral de Obras y Catastro (43) La Nueva Seguros(44) APRA - Agencia de Protección Ambiental(45) Contaduría General(46) Subsecretaría de Gestión de la Movilidad(47) Colegio Público de Abogados de la Capital Federal(48) Consejo Profesional de Ciencias Economicas CABA(49) Sub Sede Comunal N°11(50) Colegio P. De Abogados(Sede Corrientes)(51) DG Gestion de Servicios de la movilidad(52) Sub Sede Comunal Nº3 (53) Instituto Superior de Seguridad Pública(54) CIFA (APRA)(55) Parque Chacabuco(56) D.G. de Administración de Bienes(57) Dirección General de Compras y Contrataciones(58) DG Interpretación Urbanística(59) Central de Defunciones(60) Colegio Público de Abogados (Piso 4-DAI)(61) Subsede Comunal N° 2(62) Subsede Comunal N°7(63) D.G de Intervenciones en Vías Peatonales(64) Secretaria de Planeamiento (Renov Urb. ExAU3)(65) Salud (Tesoreria)(66) DGTES(67) Dirección General Suministros de Seguridad(68) Policía de la Ciudad de Buenos Aires(69) Registro de la Propiedad Inmueble(70) Registro Público de Comercio(71) Dirección General de la Mujer(72) GOTRE Transferencias(73) Hospital Santojanni(74) Sub Sede Comuna 9(75) DG. de Administración y Liquidación de Haberes(76) Hospital Zubizarreta(77) Hospital G de Agudos D. Velez Sarsfield(78) Hospital Durand(79) Hospital de Quemados(80) Hospital Fernández(81) Hospital Ramos Mejía(82) Dirección General Defensa Civil(83) Juegos Olímpicos de la Juventud(84) Dirección General Coord. Administrat. y Registros(85) Hospital General de Agudos Enrique Tornú(86) Plusvalia - DGROC(87) Juegos Olímpicos Check Out(88) Secretaría de medios(89) DG Liquidaciones y Servicios Complementarios(90) Museo del Humor(91) Secretaria de Medios(92) Ente Regulador(93) Min.Salud Donaciones COVID-19(94) Sistemas de Venta de Entrada(95) Edificio Canale(96) Oficios Judiciales(100) Complejo Golf / Velódromo(102) DIRECCION GENERAL DE CONCESIONES Y PERMISOS(103) Secretaría de Integración Social y Urbana(104) Donaciones Ba Taxi COVID-19(105) Dirección General Cuerpo de Agentes de Tránsito(106) Bomberos de la Ciudad de Bs As(107) Min. Salud Test COVID-19(108) Dirección General Diseño e Implementación(111) Planetario(112) Parque KDT(113) Parque Sarmiento(115) Parque de la Ciudad(118) Parque Samiento-Piletas(119) Parque KDT-Piletas(161) Dirección General Desarrollo Cultural y Creativo(164) DG de Coordinación Legal y Consolidación Normativa(165) Dirección General de Empleo(166) Concesiones(167) DG de Justicia, Registro y Mediación(180) DG Cementerios(200) Dependencia Prueba(873) pruebaTestPrueba(874) testDependenciaTest(901) Centro Cultural Recoleta(902) Museo Fernandez Blanco(903) Museo Jose Hernandez(904) Museo Carlos Gardel(905) Dirección General de Música(906) Casa del Virrey Liniers (Casco Histórico)(907) Centro Cultural 25 de Mayo(908) Usina del Arte(909) Ecoparque CABA(910) LS1 Radio de la Ciudad y FM 2x4(911) Señal de Cable Ciudad Abierta(912) Dirección General de Festivales y Eventos(913) Ente de Turismo(914) Centro Cultural General San Martín(915) Centro Metropolitano de Diseño(916) Complejo Teatral(917) Dirección General de Enseñanza Artística(918) Dirección General de Promoción Cultural(919) Dirección General del Libro, Bibliot y Prom Lect(920) Torre Monumental(921) Cine El Plata(922) Museo Luis Perlotti(923) Museo del Cine Pablo Ducrós Hicken(924) Museo Histórico Brigadier Cornelio Saavedra(925) Museo de Arte Moderno(926) Museo de la Ciudad(927) Museo de Arte Español Enrique Larreta(928) Museo de Artes Plásticas Eduardo Sívori(929) Museo Fernández Blanco Casa de Muñecas(930) Planta Verificadora Juramento(931) Bienal Arte Joven Buenos Aires(932) Tienda de la Cultura(933) Teatro Colón(1212) Deptest</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectDependBUI&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectDependBUI']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ng-wrapper']/div/div[2]/div[6]/div[4]/div/div[2]/span/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dependencia emisora'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conceptos del Trámite'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/span/select</value>
   </webElementXpaths>
</WebElementEntity>
