<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuReportesConsultaRecaudacionesConsolidadas</name>
   <tag></tag>
   <elementGuidId>24055776-dbb5-4bc8-a1ad-d3e0a768bcf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/nav/div/ul[3]/li/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/nav/div/ul[3]/li/ul/li[9]/a</value>
   </webElementProperties>
</WebElementEntity>
