<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuReportesConsultaRecaudaciones</name>
   <tag></tag>
   <elementGuidId>a8370b59-59ff-40e4-b26f-ee6cd1c02894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/nav/div/ul[3]/li/ul/li[8]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/nav/div/ul[3]/li/ul/li[8]/a</value>
   </webElementProperties>
</WebElementEntity>
